[WechatAPIServer]
port = 9000
mode = "release"
redis-host = "127.0.0.1"
redis-port = 6365
redis-password = ""
redis-db = 0

[XYBot]
version = "v1.0.0"
ignore-protection = true
database-url = "sqlite:///xybot.db"

admins = ["admin-wxid", "admin-wxid"]
disabled-plugins = ["ExamplePlugin"]
timezone = "Asia/Shanghai"

# 试验新功能：如果main_config.toml配置改动，或者plugins文件夹有改动，自动重启。可以在开发时使用，不建议在生产环境使用。
auto-restart = false

[OpenAI]
api-key = "sk-xxxx"
url-base = "https://api.openai.com/v1"